baseurl = "http://byzantime.github.io/"
languageCode = "en-GB"
title = "Hugo Baldwin"
newContentEditor = "subl"
theme = "slim"
pygmentsStyle = "algol"

[params]
	Subtitle = ""
	Summary = false
	Content = false
